version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
  db:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DEV_DB}
      POSTGRES_USER: ${DEV_USER}
      POSTGRES_PASSWORD: ${DEV_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${DEV_HOST_AUTH_METHOD}
    volumes:
      - db_data_dev:/var/lib/postgresql/data
volumes:
  db_data_dev:
