FROM node:latest

RUN apt-get update && apt-get install -y netcat-openbsd bash


WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install

RUN apt-get update && apt-get install -y postgresql-client


COPY . .

COPY wait-for-db.sh /usr/src/app/wait-for-db.sh
RUN chmod +x /usr/src/app/wait-for-db.sh

EXPOSE 3000


CMD ["npm", "start"]
