version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    environment:
      - NODE_ENV=production
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: ${PROD_DB}
      POSTGRES_USER: ${PROD_USER}
      POSTGRES_PASSWORD: ${PROD_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${PROD_HOST_AUTH_METHOD}
    volumes:
      - db_data_prod:/var/lib/postgresql/data
volumes:
  db_data_prod:
