version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "80:3000"
    environment:
      NODE_ENV: production
    depends_on:
      - db
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: forum_prod
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    volumes:
      - db_data_prod:/var/lib/postgresql/data

volumes:
  db_data_prod:
