version: '3.8'
services:
  app_test:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:3000"  
    environment:
      NODE_ENV: test
    depends_on:
      - db_test
  db_test:
    image: postgres:13
    environment:
      POSTGRES_DB: ${TEST_DB_NAME}
      POSTGRES_USER: ${TEST_DB_USER}
      POSTGRES_PASSWORD: ${TEST_DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${TEST_DB_HOST_AUTH_METHOD}
    volumes:
      - db_data_test:/var/lib/postgresql/data

volumes:
  db_data_test:
