version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: DockerFile
    ports:
      - "3000:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - NODE_ENV=development
  db:
    image: postgres:13
    environment:
      POSTGRES_DB: forum
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
