FROM node:latest

RUN apt-get update && apt-get install -y netcat-openbsd


WORKDIR /usr/src/app

COPY package*.json ./

RUN npm install


COPY . .


COPY wait-for-db.sh .

RUN chmod +x wait-for-db.sh

EXPOSE 3000


CMD ["npm", "start"]
