version: "3.8"
services:
  app_dev:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "80:3000"
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      NODE_ENV: development
      DB_NAME: ${DEV_DB_NAME}
      DB_USER: ${DEV_DB_USER}
      DB_PASSWORD: ${DEV_DB_PASSWORD}
      DB_HOST_AUTH_METHOD: ${DEV_DB_HOST_AUTH_METHOD}
      ACCESS_TOKEN_SECRET: ${ACCESS_TOKEN_SECRET}
  db_dev:
    image: postgres:13
    ports:
      - "5432:5432"
    environment:
      POSTGRES_DB: ${DEV_DB_NAME}
      POSTGRES_USER: ${DEV_DB_USER}
      POSTGRES_PASSWORD: ${DEV_DB_PASSWORD}
      POSTGRES_HOST_AUTH_METHOD: ${DEV_DB_HOST_AUTH_METHOD}
    volumes:
      - db_data_dev:/var/lib/postgresql/data

volumes:
  db_data_dev:
