name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: play-play
  POSTGRES_DB: forum
  DB_HOST: db_test
  TEST_DB_USER: postgres
  TEST_DB_PASSWORD: play-play
  TEST_DB_HOST_AUTH_METHOD: trust
  ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install Docker Compose
        run: |
          sudo curl -L "https://github.com/docker/compose/releases/download/v2.3.3/docker-compose-$(uname -s)-$(uname -m)" -o /usr/local/bin/docker-compose
          sudo chmod +x /usr/local/bin/docker-compose
          docker-compose --version

      - name: Change working directory to root
        run: cd $GITHUB_WORKSPACE

      - name: Build Docker containers
        run: docker-compose -f docker-compose.test.yml build

      - name: Run Docker containers
        run: |
          echo --- Running test cases ---
          docker-compose -f docker-compose.test.yml up --exit-code-from app_test
          echo --- Completed test cases ---

  build:
    needs: test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Change working directory to root
        run: cd $GITHUB_WORKSPACE

      - name: Build Docker images
        run: docker-compose build

      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker images
        run: docker-compose push
