name: CI/CD Pipeline

on:
  push:
    branches: [main]

env:
  POSTGRES_USER: postgres
  POSTGRES_PASSWORD: play-play
  POSTGRES_DB: forum
  DB_HOST: db_test

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker containers
        run: docker-compose -f docker-compose.test.yml build 

      - name: Run Docker containers and execute tests
        run: |
          echo "--- Running test cases ---"
          docker-compose -f docker-compose.test.yml up --abort-on-container-exit --exit-code-from app_test
          echo "--- Completed test cases ---"
        env:
          NODE_ENV: test
          TEST_DB_HOST: db_test
          TEST_DB_NAME: forum
          TEST_DB_USER: postgres
          TEST_DB_PASSWORD: play-play
          ACCESS_TOKEN_SECRET: ${{ secrets.ACCESS_TOKEN_SECRET }}

  build:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Build Docker image
        run: docker-compose -f docker-compose.yml build

      - name: Publish Docker image to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Push Docker image
        run: docker-compose -f docker-compose.yml push

      - name: Log out from Docker Hub
        run: docker logout
